use std::collections::HashSet;

pub fn curate_unreachable_records() -> HashSet<&'static str> {
    let mut broken_urls = HashSet::new();
    // http troubles
    broken_urls.insert("ad.yieldmanager.com");
    broken_urls.insert("lovine.com");
    broken_urls.insert("s7ondemand1.scene7.com");
    broken_urls.insert("hcr.com");
    broken_urls.insert("naver.com");
    // broken_urls.insert("diligogames.com");
    // broken_urls.insert("aim.search.aol.com");
    broken_urls.insert("mylifeisaverage.com");
    broken_urls.insert("parents.com");
    broken_urls.insert("desktopfw.weather.com");
    broken_urls.insert("ad.doubleclick.net");
    broken_urls.insert("ebates.com");
    broken_urls.insert("youtube.com");
    broken_urls.insert("images.google.com");
    broken_urls.insert("view.atdmt.com");
    broken_urls.insert("kr.sports.yahoo.com");
    broken_urls.insert("apps.facebook.com");
    broken_urls.insert("talenthunter.com");
    broken_urls.insert("blog.naver.com");
    broken_urls.insert("beacon.securestudies.com");
    broken_urls.insert("nbcsports.msnbc.com");
    broken_urls.insert("graphics.ocsn.com");
    broken_urls.insert("cyworld.com");
    broken_urls.insert("google.com");
    broken_urls.insert("farfesh.com");
    broken_urls.insert("grad2b.com");
    broken_urls.insert("gamespot.com");
    broken_urls.insert("search.yahoo.com");
    broken_urls.insert("nexplore.com");
    broken_urls.insert("nba.com");
    broken_urls.insert("nursingsociety.org");
    broken_urls.insert("gametrailers.com");
    broken_urls.insert("rockyou.com");
    broken_urls.insert("cafe427.daum.net");
    broken_urls.insert("quotationspage.com");
    broken_urls.insert("facebook.com");
    broken_urls.insert("informatics.indiana.edu");
    broken_urls.insert("people.com");
    broken_urls.insert("video-stats.video.google.com");
    broken_urls.insert("apple.com");
    broken_urls.insert("motors.shop.ebay.com");
    broken_urls.insert("myyearbook.com");
    broken_urls.insert("rs.mail.ru");
    broken_urls.insert("dataandsearch.org");
    broken_urls.insert("www2.victoriassecret.com");
    broken_urls.insert("arienh4.net.nyud.net");
    broken_urls.insert("optimized-by.rubiconproject.com");
    broken_urls.insert("movie.tudou.com");
    broken_urls.insert("vip.51.la");
    broken_urls.insert("penciloflight.deviantart.com");
    broken_urls.insert("psychonet.co.uk");
    broken_urls.insert("gaiaonline.com");
    broken_urls.insert("waterjet.net");
    broken_urls.insert("tumblr.com");
    broken_urls.insert("indiana.edu");
    broken_urls.insert("msn.foxsports.com");
    broken_urls.insert("basketball.fantasysports.yahoo.com");
    broken_urls.insert("wretch.cc");
    broken_urls.insert("api.tinypic.com");
    broken_urls.insert("6park.com");
    broken_urls.insert("t.adbuyer.com");
    broken_urls.insert("ads.revsci.net");
    broken_urls.insert("cs.indiana.edu");
    broken_urls.insert("sports.sina.com.cn");
    broken_urls.insert("diligogames.com");
    broken_urls.insert("gn.naver.com");
    broken_urls.insert("llbean.com");
    broken_urls.insert("slis.indiana.edu");
    broken_urls.insert("bing.com");
    broken_urls.insert("tudou.com");
    broken_urls.insert("reuters.com");
    broken_urls.insert("im.storm8.com");
    broken_urls.insert("focusbaiduafp.allyes.com");
    broken_urls.insert("lg15.com");
    broken_urls.insert("wired.com");
    broken_urls.insert("cfile193.uf.daum.net");
    broken_urls.insert("s7.addthis.com");
    broken_urls.insert("googleads.g.doubleclick.net");
    broken_urls.insert("mt1.google.com");
    broken_urls.insert("osl.iu.edu");
    broken_urls.insert("search.ebscohost.com");
    broken_urls.insert("search.msn.com");
    broken_urls.insert("bs.serving-sys.com");
    broken_urls.insert("l.yimg.com");
    broken_urls.insert("game3.pogo.com");
    broken_urls.insert("gdx.mlb.com");
    broken_urls.insert("mediafire.com");
    broken_urls.insert("pfp.sina.com.cn");
    broken_urls.insert("footytube.com");
    broken_urls.insert("pogo.com");
    broken_urls.insert("2pm.jype.com");
    broken_urls.insert("kr.yahoo.com");
    broken_urls.insert("target.com");
    broken_urls.insert("static.twitter.com");
    broken_urls.insert("bbc.co.uk");
    broken_urls.insert("hulu.com");
    broken_urls.insert("player.cdn.targetspot.com");
    broken_urls.insert("xanga.com");
    broken_urls.insert("tap.rubiconproject.com");
    broken_urls.insert("engadget.com");
    broken_urls.insert("search.conduit.com");
    broken_urls.insert("amazon.com");
    broken_urls.insert("m.www.yahoo.com");
    broken_urls.insert("flickr.com");
    broken_urls.insert("nytimes.com");
    broken_urls.insert("google.cn");
    broken_urls.insert("c13.zedo.com");
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();
    // broken_urls.insert();

    return broken_urls;
}
